# Generated by Django 6.0.4 on 2026-04-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metrica_errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_error', models.CharField(max_length=200)),
                ('fecha_error', models.DateTimeField(verbose_name='date published')),
                ('cantidad_errores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='metrica_front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulos', models.CharField(max_length=200)),
                ('parrafos', models.CharField(max_length=200)),
                ('botones', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='metrica_resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultados', models.CharField(max_length=200)),
                ('estadísticas', models.IntegerField(default=0)),
            ],
        ),
    ]
