# Generated by Django 6.0.4 on 2026-05-23 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('COMPUTADOR', 'Computador'), ('HDMI', 'HDMI'), ('CONTROL', 'Control'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('PROYECTOR', 'Proyector')], max_length=20)),
                ('serial', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('DAÑADO', 'Dañado'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('fecha_compra', models.DateField()),
                ('nombre_estudiante', models.CharField(blank=True, default='', max_length=200)),
                ('numero_estudiante', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='El número de estudiante debe contener exactamente 15 dígitos.', regex='^\\d{15}$')])),
            ],
        ),
    ]
