# Generated by Django 6.0.4 on 2026-05-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fecha_compra',
            new_name='fecha_solicitud',
        ),
    ]
