# Generated by Django 6.0.4 on 2026-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='equipo',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'Mantenimiento'), ('DAÑADO', 'Dañado')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('HDMI', 'HDMI'), ('CONTROL', 'Control'), ('AUDIO', 'Audio'), ('RED', 'Equipo de red'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
