# Generated by Django 6.0.4 on 2026-05-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0002_remove_prestamo_persona_remove_prestamo_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('DAÑADO', 'Dañado'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('HDMI', 'Cable HDMI'), ('AUDIO', 'Audio / Parlantes'), ('MICROFONO', 'Micrófono'), ('RED', 'Cable de red'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('PROYECTOR', 'Proyector')], max_length=20),
        ),
    ]
