# Generated by Django 6.0.4 on 2026-05-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0003_remove_equipo_nombre_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('MANTENIMIENTO', 'Mantenimiento'), ('DAÑADO', 'Dañado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(choices=[('DELL', 'Dell'), ('HP', 'HP'), ('LENOVO', 'Lenovo'), ('APPLE', 'Apple'), ('ASUS', 'Asus'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('PC', 'PC'), ('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('IMPRESORA', 'Impresora')], max_length=20),
        ),
    ]
