# Generated by Django 6.0.4 on 2026-05-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0004_alter_equipo_estado_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('DAÑADO', 'Dañado'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(choices=[('DELL', 'Dell'), ('HP', 'HP'), ('LENOVO', 'Lenovo'), ('ASUS', 'Asus'), ('APPLE', 'Apple'), ('OTRA', 'Otra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('HDMI', 'HDMI'), ('CONTROL', 'Control'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('PROYECTOR', 'Proyector')], max_length=20),
        ),
    ]
