# Generated by Django 6.0.4 on 2026-05-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0005_alter_equipo_estado_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=100),
        ),
    ]
