# Generated by Django 6.0.4 on 2026-05-23 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_equipos', '0006_alter_equipo_marca_alter_equipo_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nombre_estudiante',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_estudiante',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='El número de estudiante debe contener exactamente 15 dígitos.', regex='^\\d{15}$')]),
        ),
    ]
